apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: fastdfs-exporter
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: fastdfs-exporter
    spec:
      containers:
      - name: fastdfs-exporter
        image: registry.cn-hangzhou.aliyuncs.com/nevermore/fastdfs-exporter:v0.1
        ports:
        - containerPort: 10000
        env:
          - name: APISERVER
            value: "http://localhost:8080"    #change to APISERVER address 
          - name: FASTDFS_POD_NAME
            value: "fastdfs"                  #change to APISERVER address fastdfs pod name
          - name: NAMESPACE
            value: "default"                  #change to fastdfs pod's namespace
        volumeMounts:
        - name: sys-time
          mountPath: /etc/localtime
      volumes:
        - name: sys-time
          hostPath:
            path: /etc/localtime