apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: fastdfs-exporter
  namespace: monitoring
  labels:
    app: fastdfs-exporter
spec:
  ports:
  - name: fastdfs-exporter
    port: 10000
    targetPort: 10000
    protocol: TCP
  selector:
    app: fastdfs-exporter